### ISSUE TITLE
MakeInstall.bat error "no usable free extent could be found"

### ISSUE THREAD

**Issue by filamento** [corpnewt/gibMacOS#1]
Hi,

I'm trying to run the makeinstall.bat script, but I always get the same "no usable free extent could be found" error.

I've tried several brands of usb flash drives, and even SD cards with an USB reader, but the error persists.

I've also tried a SATA drive inside a USB cage, but it doesn't even appear in the list to choose it!!

**Comment by corpnewt** [comment]
What version of Windows are you running?  DiskPart is terribly picky - and that's what's failing (although sometimes its failures aren't even failures - for reasons unknown).  If you're not on the latest Windows 10 version, you could try updating and see if that helps.

**Comment by filamento** [comment]
You're right!

I was trying with my main PC, which is running Win10 version 1607. 

Now I've tested it on my laptop (which is running Win10 version 1809) and it runs the script correctly!

Thanks a lot! :)

**Comment by corpnewt** [comment]
Not a problem, glad it was a simple fix!

-CorpNewt

**Comment by Antikapitalista** [comment]
No, that was no fix, this problem still exists!

This is probably due to the known limitation of Windows that it does not support creating additional partitions on removable storage media.
This limitation apparently exists in builds numbered 14393, i.e. the above-mentioned Windows 10 version 1607 Anniversary Edition, Windows 10 Enterprise 2016 Long-Term Servicing Branch, Windows Server 2016 and possibly others.

Diskpart chokes on the last command to create an additional primary partition and exits with the following message:

"No usable free extent could be found. It may be that there is insufficient free space to create a partition at the specified size and offset. Specify different size and offset values or don't specify either to create the maximum sized partition. It may be that the disk is partitioned using the MBR disk partitioning format and the disk contains either 4 primary partitions, (no more partitions may be created), or 3 primary partitions and one extended partition, (only logical drives may be created)."

Anyway, the script is horrible in that if it something goes wrong, it quite inexplicably conceals its mess by deleting its traces, so that the user may not know what went wrong and why.
