### ISSUE TITLE
Why networking is required for installation?

### ISSUE THREAD

**Issue by bininc** [corpnewt/gibMacOS#230]
The volume of the download installation package is also very large. Why do you need to connect with the Internet?

**Comment by corpnewt** [comment]
I would need more info on what you're doing to fully answer that - but without more, I'll assume you're building an install USB on Windows:

gibMacOS can download the full install packages for different macOS versions, but MakeInstall can *only* create recovery installers.  This is due to Windows' inability to work with HFS+ file systems - read/write access is needed to manipulate the packages downloaded into a full install .app (and to create a full USB installer).  Since Windows does not have this capability built-in, MakeInstall only `dd`s the file system from the recovery package's BaseSystem.dmg to the USB drive (which does not require it interprets the contents, just copies from source to destination).

Given this limitation on Windows - but the fact that gibMacOS can be run wherever python works, there is an option to download *only* the recovery environments, which is useful for use with MakeInstall as it omits the other files, saving you download time.

For the time being, this is not a fault of the script - and unless there is enough evidence to imply that it is, I'll close this issue (I'll reopen if other script-based issues are brought to light though).

-CorpNewt
