### ISSUE TITLE
Missing bat version of a script

### ISSUE THREAD

**Issue by michelle1574** [corpnewt/gibMacOS#254]
The script name is MakeInstallApp or something like that
and it has Py and command version of this and there is no Windows version of that script
Py script is only for Mac also, so there is no way for Linux users.

**Comment by corpnewt** [comment]
There is no Windows or Linux version because it relies on HFS+ read/write support natively, and the ability to open, explore, and work with dmgs.  This approach is also only applied to Catalina and prior - as with Big Sur Apple changed how their installer is distributed - you would just run the InstallAssistant.pkg instead of needing to repack the other components.

-CorpNewt

**Comment by michelle1574** [comment]
But when installing InstallAssistant.pkg says Insert disc (null), is it an error?
Or is it a package problem?
