### ISSUE TITLE
Python Syntax Error

### ISSUE THREAD

**Issue by atw58** [corpnewt/gibMacOS#261]
I followed the instructions to create a OpenCore Install USB (https://www.youtube.com/watch?v=eUnVzJsINCI). At 12:10 he started to downloading the Mac OS using "python gitMacOS.command". When I tried a python syntax error occurred at line 9 - "NL=$'n'". Removing the $, another error occurred.
[gibMacOS-master.zip](https://github.com/corpnewt/gibMacOS/files/8642431/gibMacOS-master.zip)

**Comment by corpnewt** [comment]
Hey there - that video is outdated. If you are piping the script to the interpreter directly, you'll need to pipe gibMacOS.py, not the .command (which is bash).

-CorpNewt

**Comment by atw58** [comment]
Many thanks. I'm not a coding/linux/python expert just an old electrical engineer who spent 1.5 hrs looking up all manner of solutions. I know enough to be dangerous.

**Comment by corpnewt** [comment]
All good - I ended up going from python .command starters to bash because Apple no longer ships python with the OS as of 12.3.  The bash starters are still double-click to run, pass arguments, etc - but they check if python is in the local path variable, and if not - can download and install it for the user (making the whole experience still relatively transparent and fluid).

Glad we got it figured out though 👍 

-CorpNewt
