### ISSUE TITLE
After installing clover: No partitions located on disk error.

### ISSUE THREAD

**Issue by WamyPlayz** [corpnewt/gibMacOS#29]
![Capture](https://user-images.githubusercontent.com/25761442/67432514-01823000-f5ac-11e9-86fe-54aa442e821d.PNG) Here you can see the problem. It makes me press enter and when I do the drive cannot be located in explorer, although it shows up in disk manager.

**Comment by corpnewt** [comment]
Per [this](https://github.com/corpnewt/gibMacOS/issues/13) and [this](https://github.com/corpnewt/gibMacOS/issues/23) issue:
>Typically denotes one of the following:
>
>* You may be using a third party partitioning or disk management software that interferes
>* The USB may be faulty
>* Windows/DiskPart may be misconfigured

You can try updating Windows, changing USB drives, uninstalling any 3rd party disk management software - or trying on another machine.  This problem seems to be related to variables beyond this script though - so I'm going to close the issue.

-CorpNewt
