### ISSUE TITLE
MakeInstall problem 

### ISSUE THREAD

**Issue by liuchunxiao** [corpnewt/gibMacOS#295]
i have a  MakeInstall problem . My two  flash drive （16GB and 32GB） all  encountered this problem,As shown below, how to solve it?

![111](https://github.com/corpnewt/gibMacOS/assets/8477814/42eafbeb-b558-4889-bfe0-57b3187b6d6c)

**Comment by corpnewt** [comment]
Windows' `diskpart` can be quite picky.  I added the option to MakeInstall to prevent it from formatting the disk itself, and just use the partitioning as-is.  This requires you format the disk using some other tool ahead of time though.

Per the main menu of MakeInstall, you'll want to include `F` in your command to have it skip formatting:
```
    F = Skip formatting the disk - will install the boot manager to the first
        partition, and dd the recovery image to the second.
```

In order to properly format the device ahead of time, you'll need 2 partitions.  The first should be a 200 (or so) MB FAT32 partition, this is where the EFI will reside.  The second needs to be a RAW partition of a size large enough to hold the HFS+ image for the recovery environment (usually 1GB or more).  It is important that it is a RAW partition, as MakeInstall uses dd to write the contents of the BaseSystem.dmg to the partition - and Windows cannot natively read/write HFS+ - so it needs a blank canvas per se for that data.

-CorpNewt

**Comment by liuchunxiao** [comment]
thanks.However, I use DiskGenius software, but I cannot find the function of creating a raw partition in GPT mode. How can I create a raw partition? Should I use the diskpart tool that comes with the system? Or is there any other better software?

**Comment by corpnewt** [comment]
The `diskpart` that MakeInstall uses *is* the one that comes with the system.  It just generates a script for that to run with the disk info filled out - and pipes it to `diskpart` via the `/s` switch.  You might have luck using Disk Management - which acts like a GUI front-end to `diskpart` - but that may also encounter the same issues.

I'm not sure how to do the formatting in DiskGenius though, as it's not something I've ever used.

-CorpNewt
